// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PGV8F3tqQgLJONlZpL42sRGFlfV2q20',
    appId: '1:480934611158:web:dfda73a06b2fa443592177',
    messagingSenderId: '480934611158',
    projectId: 'vivant-24bb2',
    authDomain: 'vivant-24bb2.firebaseapp.com',
    storageBucket: 'vivant-24bb2.firebasestorage.app',
    measurementId: 'G-2TMRQPXZNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdEv3Mh-idmZr9cTBLwOqrT0hYiKBqaU',
    appId: '1:480934611158:android:2fb8ef0ef40cf1c2592177',
    messagingSenderId: '480934611158',
    projectId: 'vivant-24bb2',
    storageBucket: 'vivant-24bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvHHVi1fC-FCWC_Zst64khN7RNp_hbPgQ',
    appId: '1:480934611158:ios:efd8ee74b5a9fae8592177',
    messagingSenderId: '480934611158',
    projectId: 'vivant-24bb2',
    storageBucket: 'vivant-24bb2.firebasestorage.app',
    iosBundleId: 'com.gammagamma.vivant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvHHVi1fC-FCWC_Zst64khN7RNp_hbPgQ',
    appId: '1:480934611158:ios:efd8ee74b5a9fae8592177',
    messagingSenderId: '480934611158',
    projectId: 'vivant-24bb2',
    storageBucket: 'vivant-24bb2.firebasestorage.app',
    iosBundleId: 'com.gammagamma.vivant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0PGV8F3tqQgLJONlZpL42sRGFlfV2q20',
    appId: '1:480934611158:web:9d0da353c415a5c5592177',
    messagingSenderId: '480934611158',
    projectId: 'vivant-24bb2',
    authDomain: 'vivant-24bb2.firebaseapp.com',
    storageBucket: 'vivant-24bb2.firebasestorage.app',
    measurementId: 'G-TLR02MBFJ5',
  );

}